name: neutroncoin-wallet
version: '1.1.1'
summary: Cryptocurrency Wallet for Neutron
description: |
 A Cryptocurrency that operates by Proof of Stake. Neutron is no longer minable and requires no 
 expensive equipment to participate. By simply holding a balance in an open, encrypted wallet you 
 are awarded stakes in proportion to the amount you hold for verifying transactions and helping 
 to keep the network secure. You can earn additional coins by participating in the "Nucleus Node" 
 system, which rewards participants for operating a node on the Neutron network. Whether you're an 
 expert or only just getting started, Neutron is a safe, green, and stable coin which allows you to 
 store value digitally and generate income in NTRN, based simply on the amount you hold. It is easier 
 than ever to buy, stake, and trade.

grade: stable
confinement: classic
icon: icons/neutron-wallet.png

apps:
  neutroncoin-wallet:
    command: desktop-launch $SNAP/Neutron-qt -datadir=$HOME
    plugs:
      - network
      - network-bind
      - x11
      - home
      - unity7

parts:
  neutroncoin-wallet:
    plugin: qmake
    source: https://github.com/audiotopix/Neutron.git
    options: ["USE_UPNP=-"]
    qt-version: "qt5"
    build:
      qmake -qt=qt5 USE_PNP=- && make && strip Neutron-qt
    install:
      mv ../build/Neutron-qt $SNAPCRAFT_PART_INSTALL
    build-packages:
      - libboost-all-dev
      - libssl-dev
      - libqrencode-dev
    after:
      - libdb
      - desktop-qt5
  libdb:
    plugin: autotools
    source: http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
    build: |
      cd ./build_unix
      ../dist/configure --enable-cxx
      make
      sudo make install
    artifacts:
      - libdb_cxx-4.8.so
      - libdb-4.8.so
  icons:
    plugin: dump
    source: icons
    organize:
      neutron-wallet.png: usr/share/neutron-wallet.png
